title: Nikolas Charalambidis
description: ""

baseurl: "/"
url: "https://nikolas-charalambidis.github.io"
email: nikolas.charalambidis@gmail.com

# Pagination
paginate: 4
permalink: /blog/:year/:title/
paginate_path: /blog/page:num/

# Social media links in footer
linkedin: "nikolas-charalambidis/"
stackoverflow: "3764965/nikolas-charalambidis?tab=profile"
github: "Nikolas-Charalambidis"
facebook: "nikolas.charalambidis/"
#twitter: "#"
#researchgate: "#"
#orcid: "#"
#quora: "#"
#instagram: "#"

# Markdown
highlighter: rouge
markdown: kramdown

# Tracker
analytics:
  measurement_id: G-N2VS12CVCD

# optimization -> compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []

#collection
collections:
  projects:
    output: true
    permalink: /projects/:name/
    order:
      - website.md
      - interviews.md
      - school.md

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - README.md
  - LICENSE.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-email-protect
  - jekyll-target-blank
